services:
  db:
    image: postgres:18
    container_name: ${CONTAINER_NAME:-boilerplate-postgres}
    environment:
      POSTGRES_DB: ${DB_NAME:-boilerplate}
      POSTGRES_USER: ${DB_USER:-boilerplate}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
    ports:
      - "${DB_PORT:-5000}:5432"
    volumes:
      - boilerplate_postgresql_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  boilerplate_postgresql_data:
    name: ${CONTAINER_NAME:-boilerplate-postgres-data}
